# Generated by Django 4.1 on 2022-09-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
        migrations.AlterField(
            model_name="ficatr",
            name="atributo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FicAtr",
                to="core.atributo",
            ),
        ),
        migrations.AlterField(
            model_name="ficatr",
            name="ficha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FicAtr",
                to="core.ficha",
            ),
        ),
        migrations.AlterField(
            model_name="ficha",
            name="orig",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichas",
                to="core.origem",
            ),
        ),
        migrations.AlterField(
            model_name="ficha",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ficper",
            name="ficha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FicPer",
                to="core.ficha",
            ),
        ),
        migrations.AlterField(
            model_name="ficper",
            name="pericia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PerFic",
                to="core.pericia",
            ),
        ),
        migrations.AlterField(
            model_name="origem",
            name="pericia1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.pericia",
            ),
        ),
        migrations.AlterField(
            model_name="origem",
            name="pericia2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.pericia",
            ),
        ),
    ]
