# Generated by Django 4.1 on 2022-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ficatr",
            options={"verbose_name_plural": "FichaAtributos"},
        ),
        migrations.AlterModelOptions(
            name="ficper",
            options={"verbose_name_plural": "FichaPericias"},
        ),
        migrations.AddField(
            model_name="origem",
            name="pericias",
            field=models.ManyToManyField(related_name="origens", to="core.pericia"),
        ),
    ]
