# Generated by Django 4.1.2 on 2022-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="origem",
            old_name="poder",
            new_name="poderdesc",
        ),
        migrations.AddField(
            model_name="origem",
            name="podernome",
            field=models.TextField(default=None, max_length=40),
        ),
    ]
