# Generated by Django 4.1.1 on 2022-10-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField(max_length=40)),
                ("pvIni", models.IntegerField(default=0)),
                ("pvMod", models.IntegerField(default=0)),
                ("peIni", models.IntegerField(default=0)),
                ("peMod", models.IntegerField(default=0)),
                ("snIni", models.IntegerField(default=0)),
                ("snMod", models.IntegerField(default=0)),
                (
                    "habilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.poder",
                    ),
                ),
                (
                    "habilidade2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.poder",
                    ),
                ),
                ("profi", models.ManyToManyField(to="core.proficiencia")),
            ],
        ),
        migrations.AddField(
            model_name="trilha",
            name="classe",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.classe",
            ),
        ),
    ]
