# Generated by Django 4.1.1 on 2022-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trilha",
            name="descNex10",
            field=models.TextField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name="trilha",
            name="descNex30",
            field=models.TextField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name="trilha",
            name="descNex65",
            field=models.TextField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name="trilha",
            name="descNex99",
            field=models.TextField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name="trilha",
            name="nomeNex10",
            field=models.TextField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name="trilha",
            name="nomeNex30",
            field=models.TextField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name="trilha",
            name="nomeNex65",
            field=models.TextField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name="trilha",
            name="nomeNex99",
            field=models.TextField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
