# Generated by Django 4.1 on 2022-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atributo",
            name="grau_pericia",
        ),
        migrations.AddField(
            model_name="ficper",
            name="grau_pericia",
            field=models.IntegerField(
                choices=[
                    (1, "Destreinado"),
                    (2, "Treinado"),
                    (3, "Veterano"),
                    (4, "Expert"),
                ],
                default=1,
            ),
        ),
    ]
