# Generated by Django 4.1 on 2022-09-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AtrFic",
        ),
    ]
