# Generated by Django 4.1 on 2022-09-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0002_ficha_foto_alter_ficatr_atributo_alter_ficatr_ficha_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
    ]
