# Generated by Django 4.1 on 2022-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_atrfic"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="atributos",
            field=models.ManyToManyField(related_name="fichas", to="core.atributo"),
        ),
    ]
