# Generated by Django 4.1.2 on 2022-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_poder_origem_poderdesc_origem_podernome"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="media/perfil"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="media/perfil"),
        ),
    ]
