# Generated by Django 4.0.6 on 2022-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login_user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome_user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
