# Generated by Django 4.1.1 on 2022-10-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_classe_trilha_classe"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="numpericias",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
