# Generated by Django 4.1 on 2022-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_atributo_grau_pericia_ficper_grau_pericia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proficiencia",
            fields=[
                (
                    "id_proficiancia",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nome_proficiencia", models.CharField(max_length=40)),
            ],
        ),
    ]
