# Generated by Django 4.1.1 on 2022-10-04 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_classe_numpericias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fichario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fichario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
