# Generated by Django 4.1 on 2022-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_usuario_cpf_remove_usuario_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
