# Generated by Django 4.0.6 on 2022-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_login_user_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_user',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
    ]
