# Generated by Django 4.1.2 on 2022-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ficha_foto_usuario_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="imagem",
            field=models.FileField(blank=True, null=True, upload_to="ficha/"),
        ),
    ]
