# Generated by Django 4.1.1 on 2022-10-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fichario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ficha",
            old_name="orig",
            new_name="origem",
        ),
        migrations.RenameField(
            model_name="ficha",
            old_name="user",
            new_name="usuario",
        ),
        migrations.AddField(
            model_name="ficha",
            name="fichario",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fichas",
                to="core.fichario",
            ),
        ),
    ]
