# Generated by Django 4.0.6 on 2022-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login_user',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
