# Generated by Django 4.1.2 on 2022-12-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_ficha_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ficha",
            name="pericias",
        ),
        migrations.RemoveField(
            model_name="ficper",
            name="grau",
        ),
    ]
