# Generated by Django 4.0.6 on 2022-08-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id_origem', models.AutoField(primary_key=True, serialize=False)),
                ('nome_origem', models.CharField(default=None, max_length=50)),
                ('desc_origem', models.TextField(default=None, max_length=1000)),
                ('poder_origem', models.TextField(default=None, max_length=400)),
            ],
        ),
    ]
