# Generated by Django 4.1.1 on 2022-10-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_orig_ficha_origem_rename_user_ficha_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichas",
                to="core.classe",
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="poderes",
            field=models.ManyToManyField(related_name="fichas", to="core.poder"),
        ),
        migrations.AddField(
            model_name="ficha",
            name="trilha",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichas",
                to="core.trilha",
            ),
        ),
    ]
