# Generated by Django 4.0.6 on 2022-08-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origem',
            options={'verbose_name_plural': 'Origens'},
        ),
    ]
