# Generated by Django 4.1.1 on 2022-10-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_ficha_classe_ficha_poderes_ficha_trilha"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poder",
            options={"verbose_name_plural": "Poderes"},
        ),
        migrations.AddField(
            model_name="arma",
            name="ficha",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ficha",
            ),
        ),
        migrations.AddField(
            model_name="utilitario",
            name="ficha",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ficha",
            ),
        ),
        migrations.AddField(
            model_name="vestimenta",
            name="ficha",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ficha",
            ),
        ),
    ]
