# Generated by Django 4.0.6 on 2022-08-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_origem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id_pericia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pericia', models.CharField(max_length=40)),
                ('desc_pericia', models.TextField(max_length=255)),
                ('penalidade_carga', models.BooleanField(default=False)),
                ('somente_treinado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='password_user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='active_user',
            field=models.BooleanField(default=True),
        ),
    ]
