# Generated by Django 4.1.1 on 2022-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_ficper_options_alter_origem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ficha",
            name="poderes",
            field=models.ManyToManyField(
                blank=True, related_name="fichas", to="core.poder"
            ),
        ),
    ]
