# Generated by Django 4.0.6 on 2022-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pericia_rename_password_usuario_password_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=255)),
                ('desc_item', models.CharField(max_length=255)),
                ('espaco_item', models.IntegerField(default=1)),
                ('num_dados', models.IntegerField(default=None)),
                ('tipo_dado', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilitario',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=255)),
                ('desc_item', models.CharField(max_length=255)),
                ('espaco_item', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vestimenta',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=255)),
                ('desc_item', models.CharField(max_length=255)),
                ('espaco_item', models.IntegerField(default=1)),
                ('modificador_esq', models.IntegerField(default=None)),
                ('modificador_pas', models.IntegerField(default=None)),
                ('modificador_blo', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'abstract': False,
            },
        ),
    ]
