# Generated by Django 4.0.6 on 2022-08-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_arma_utilitario_vestimenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_atributo', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='arma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilitario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vestimenta',
            options={},
        ),
    ]
