# Generated by Django 4.1.1 on 2022-10-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_poder_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trilha",
            old_name="descNex30",
            new_name="descNex40",
        ),
        migrations.RenameField(
            model_name="trilha",
            old_name="nomeNex30",
            new_name="nomeNex40",
        ),
    ]
