# Generated by Django 4.0.6 on 2022-08-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ficha_ficper_atrfic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficper',
            name='id_fic_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FicPer', to='core.ficha'),
        ),
        migrations.AlterField(
            model_name='ficper',
            name='id_per_fic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PerFic', to='core.pericia'),
        ),
    ]
