# Generated by Django 4.1.1 on 2022-10-14 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_descnex30_trilha_descnex40_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichario",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ficharios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
