# Generated by Django 4.1 on 2022-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_ficha_nex_ficha_vida_atu_ficha_vida_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="sani_atu",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ficha",
            name="sani_max",
            field=models.IntegerField(default=0),
        ),
    ]
